- .github/workflows/tests.yml
- README.md
> style: update README and improve ci

- shared/id/id.go
- shared/mongo/objid/objid.go
optimize
Create objective id to replace origin.
None.
> optimize: create objective id to replace origin

- server/cmd/profile/dao/mongo.go
- server/cmd/profile/handler.go
- shared/id/id.go
- shared/mongo/objid/objid.go
> chore: delete some useless function and use filed id to replace authid

- go.mod
- go.sum
- server/cmd/api/biz/model/car/car.go
- server/cmd/car/config/config.go
- server/cmd/car/dao/mongo.go
- server/cmd/car/global/global.go
- server/cmd/car/handler.go
- server/cmd/car/initialize/car.go
- server/cmd/car/initialize/config.go
- server/cmd/car/initialize/db.go
- server/cmd/car/initialize/trip.go
- server/cmd/car/main.go
- server/cmd/car/tool/mq/amqpclt/amqp.go
- server/cmd/car/tool/sim/sim.go
- server/cmd/car/tool/trip/updater.go
- server/cmd/car/tool/ws/ws.go
> feat: complete carService

- server/cmd/api/biz/handler/car/car_service.go
> optimize: improve car api bind part

- server/cmd/car/tool/sim/sim.go
> feat: auto create car in simSrv

- server/cmd/car/main.go
> fix: prevents the car service from exiting directly

- server/cmd/api/config/config.go
- server/cmd/car/car_test.go
- server/cmd/car/dao/mongo.go
- server/cmd/car/kitex_gen/car/car.go
- server/cmd/car/kitex_gen/car/k-car.go
- server/cmd/car/tool/sim/sim.go
- server/cmd/car/tool/trip/updater.go
- server/idl/car.thrift
> test: add car ut

- server/cmd/car/car_test.go
- server/cmd/profile/profile_test.go
- server/cmd/trip/trip_test.go
test
Add trip test and fix other tests' error
None.
> test: add trip test and fix other tests' error

- server/cmd/api/biz/handler/api/api_service.go
> refactor: using api request

- server/cmd/api/biz/handler/api/api_service.go
- server/cmd/car/initialize/logger.go
> fix: logger & return

- server/cmd/profile/handler.go
- shared/consts/consts.go
> fix: complete profile api

- server/cmd/api/biz/handler/api/api_service.go
- server/cmd/car/tool/sim/sim.go
- server/cmd/car/tool/trip/updater.go
- static/app.json
- static/pages/driving/driving.ts
- static/pages/index/index.ts
- static/pages/lock/lock.ts
- static/service/trip.ts
> feat: joint debugging

- server/cmd/api/initialize/registry.go
- static/pages/index/index.ts
- static/service/car.ts
- static/service/profile.ts
- static/service/request.ts
- static/service/trip.ts
> refactor: modify api

- server/cmd/api/initialize/registry.go
- server/cmd/auth/initialize/registry.go
- server/cmd/auth/main.go
- server/cmd/blob/initialize/registry.go
- server/cmd/blob/main.go
- server/cmd/car/initialize/registry.go
- server/cmd/car/main.go
- server/cmd/profile/initialize/registry.go
- server/cmd/profile/main.go
- server/cmd/trip/initialize/registry.go
- server/cmd/trip/main.go
> optimize: use net.JoinHostPort to splice address

- server/cmd/api/biz/handler/api/api_service.go
- server/cmd/api/biz/model/server/cmd/api/api.pb.go
- server/cmd/api/biz/router/api/api.go
- server/cmd/api/biz/router/api/middleware.go
- server/cmd/auth/handler.go
- server/cmd/auth/handler_test.go
- server/cmd/auth/pkg/mysql/user.go
- server/cmd/auth/pkg/mysql/user_test.go
- server/idl/api.proto
- server/idl/auth.thrift
- server/shared/kitex_gen/auth/auth.go
- server/shared/kitex_gen/auth/authservice/authservice.go
- server/shared/kitex_gen/auth/authservice/client.go
- server/shared/kitex_gen/auth/k-auth.go
> feat: add backstage management service for auth part

- docker-compose.yaml
- server/cmd/auth/handler.go
- server/idl/auth.thrift
- server/shared/kitex_gen/auth/auth.go
- server/shared/kitex_gen/auth/k-auth.go
> chore: fix auth handler

- server/cmd/api/biz/handler/api/api_service.go
- server/cmd/api/biz/router/api/middleware.go
- server/cmd/profile/handler.go
- server/cmd/profile/main.go
- server/cmd/user/handler.go
- server/cmd/user/pkg/wechat/wechat.go
- server/shared/middleware/client.go
- server/shared/middleware/common.go
- server/shared/middleware/server.go
> fix: fix bugs

- server/cmd/api/biz/handler/car/car_service.go
- server/cmd/api/biz/handler/profile/profile_service.go
- server/cmd/api/biz/handler/trip/trip_service.go
- server/cmd/api/biz/handler/user/user_service.go
- server/cmd/api/main.go
- server/cmd/api/router.go
- server/shared/errno/errno.go
- server/shared/middleware/jwt.go
> fix: fix defer bug and remove sendResponse

- server/cmd/car/pkg/mongo/mongo_test.go
- server/cmd/car/pkg/redis/redis_test.go
> test: fix test

- server/cmd/api/biz/handler/profile/profile_service.go
> fix: fix profile bug

- server/cmd/api/biz/router/common/common.go
- server/cmd/user/handler.go
> fix: fix err handling and admin paseto bug

- server/cmd/api/biz/router/common/common.go
> fix: fix account id bug

- server/cmd/car/pkg/sim/sim.go
> feat: refactor car sim
